#!/bin/sh
setxkbmap -layout br &
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
       eval `dbus-launch --sh-syntax --exit-with-session`
fi
/usr/bin/gentoo-pipewire-launcher &
transmission-daemon &
mpd &
setbg &
spoon &
