#!/bin/bash

source "${HOME}/.cache/wal/colors.sh"

echo "
dwm.normbgcolor:${background}
dwm.normfgcolor:${foreground}
dwm.normbordercolor:${color8}
dwm.selbgcolor:${color2}
dwm.selfgcolor:${foreground}
dwm.selbordercolor:${color7}
dwm.urgbgcolor:${color1}
dwm.urgfgcolor:${foreground}
dwm.urgbordercolor:${color1}
" >> ~/.Xresources
